In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [69]:
df = pd.read_csv('train_data.csv')
df.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,symptoms_count,symptoms_list,vitamin_deficiency
0,79,Male,24.8,Former,NaN,Active,Vegetarian,High,High,Mid,...,147.3,152.88,97.5,102.5,188.9,108.3,97.4,0,NaN,0.0000
1,77,Female,39.9,Former,Moderate,Light,Omnivore,Low,Low,Low,...,57.5,32.76,82.7,62.6,51.0,42.6,102.5,1,bone_pain,0.8440
2,24,Male,26.4,Former,Heavy,Moderate,Omnivore,Low,High,High,...,152.1,94.99,169.3,136.2,116.6,136.3,86.4,2,dry_skin;night_blindness,0.0040
3,69,Male,23.1,Never,Heavy,Moderate,Vegetarian,High,Low,Low,...,51.0,51.48,85.7,31.8,66.5,76.5,60.8,2,numbness_tingling;memory_problems,0.7724
4,63,Male,29.6,Never,NaN,Moderate,Vegetarian,Moderate,High,Low,...,111.5,62.90,155.6,72.6,124.9,69.4,71.9,0,NaN,0.3720

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      3500 non-null   int64
 1   gender                   3500 non-null   str
 2   bmi                      3500 non-null   float64
 3   smoking_status           3500 non-null   str
 4   alcohol_consumption      2390 non-null   str
 5   exercise_level           3500 non-null   str
 6   diet_type                3500 non-null   str
 7   sun_exposure             3500 non-null   str
 8   income_level             3500 non-null   str
 9   latitude_region          3500 non-null   str
 10  vitamin_a_percent_rda    3500 non-null   float64
 11  vitamin_c_percent_rda    3500 non-null   float64
 12  vitamin_d_percent_rda    3500 non-null   float64
 13  vitamin_e_percent_rda    3500 non-null   float64
 14  vitamin_b12_percent_rda  3500 non-null   float64
 15  folate_percent_rda       3500 non-null   float64
 16  calcium_percent_rda      3500 non-null   float64
 17  iron_percent_rda         3500 non-null   float64
 18  symptoms_count           3500 non-null   int64
 19  symptoms_list            2348 non-null   str
 20  vitamin_deficiency       3500 non-null   float64
dtypes: float64(10), int64(2), str(9)
memory usage: 574.3 KB

In [71]:
df['alcohol_consumption'].value_counts()

alcohol_consumption
Moderate    1202
Heavy       1188
Name: count, dtype: int64

In [72]:
df['symptoms_list'].value_counts()

symptoms_list
numbness_tingling;memory_problems                                                                       211
bone_pain;muscle_weakness                                                                               167
numbness_tingling                                                                                       110
bone_pain                                                                                               104
fatigue                                                                                                  97
                                                                                                       ...
dry_skin;muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;night_blindness;pale_skin;fatigue      1
dry_skin;numbness_tingling;bleeding_gums;night_blindness;memory_problems                                  1
dry_skin;muscle_weakness;bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue                    1
numbness_tingling;bleeding_gums;fatigue;night_blindness                                                   1
dry_skin;bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue                                    1
Name: count, Length: 228, dtype: int64

In [73]:
df['vitamin_deficiency'].describe()

count    3500.000000
mean        0.653209
std         0.445086
min         0.000000
25%         0.255800
50%         0.656000
75%         1.022050
max         1.890000
Name: vitamin_deficiency, dtype: float64

In [74]:
df['age'].describe()

count    3500.000000
mean       50.591714
std        19.279577
min        18.000000
25%        34.000000
50%        50.000000
75%        67.000000
max        84.000000
Name: age, dtype: float64

In [75]:
df['bmi'].describe()

count    3500.000000
mean       26.098914
std         4.944079
min        15.000000
25%        22.800000
50%        26.200000
75%        29.400000
max        43.900000
Name: bmi, dtype: float64

In [76]:
df['gender'].value_counts()

gender
Male      1781
Female    1719
Name: count, dtype: int64

In [77]:
df['smoking_status'].value_counts()

smoking_status
Current    1172
Former     1165
Never      1163
Name: count, dtype: int64

In [78]:
df['exercise_level'].value_counts()

exercise_level
Sedentary    903
Light        884
Active       866
Moderate     847
Name: count, dtype: int64

In [79]:
df['diet_type'].value_counts()

diet_type
Vegan          887
Pescatarian    876
Omnivore       870
Vegetarian     867
Name: count, dtype: int64

In [80]:
df['sun_exposure'].value_counts()

sun_exposure
Moderate    1187
High        1170
Low         1143
Name: count, dtype: int64

In [81]:
df['income_level'].value_counts()

income_level
Low       1187
High      1182
Middle    1131
Name: count, dtype: int64

In [82]:
df['latitude_region'].value_counts()

latitude_region
High    1187
Low     1175
Mid     1138
Name: count, dtype: int64

In [83]:
df['alcohol_consumption'] = df['alcohol_consumption'].fillna("does not drink")

In [84]:
df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})

df['smoking_status'] = df['smoking_status'].map({'Current': 0, 'Former': 1, 'Never': 2})
df['alcohol_consumption'] = df['alcohol_consumption'].map({'does not drink': 0, 'Moderate': 1, 'Heavy': 2})

df['exercise_level'] = df['exercise_level'].map({'Sedentary': 0, 'Light': 1, 'Moderate': 2, 'Active': 3})
df['diet_type'] = df['diet_type'].map({'Vegan': 0, 'Pescatarian': 1, 'Vegetarian': 2, 'Omnivore': 3})

df['sun_exposure'] = df['sun_exposure'].map({'Low': 0, 'Moderate': 1, 'High': 2})
df['income_level'] = df['income_level'].map({'Low': 0, 'Middle': 1, 'High': 2})
df['latitude_region'] = df['latitude_region'].map({'Low': 0, 'Mid': 1, 'High': 2})

In [85]:
df.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,vitamin_c_percent_rda,vitamin_d_percent_rda,vitamin_e_percent_rda,vitamin_b12_percent_rda,folate_percent_rda,calcium_percent_rda,iron_percent_rda,symptoms_count,symptoms_list,vitamin_deficiency
0,79,0,24.8,1,0,3,2,2,2,1,...,147.3,152.88,97.5,102.5,188.9,108.3,97.4,0,NaN,0.0000
1,77,1,39.9,1,1,1,3,0,0,0,...,57.5,32.76,82.7,62.6,51.0,42.6,102.5,1,bone_pain,0.8440
2,24,0,26.4,1,2,2,3,0,2,2,...,152.1,94.99,169.3,136.2,116.6,136.3,86.4,2,dry_skin;night_blindness,0.0040
3,69,0,23.1,2,2,2,2,2,0,0,...,51.0,51.48,85.7,31.8,66.5,76.5,60.8,2,numbness_tingling;memory_problems,0.7724
4,63,0,29.6,2,0,2,2,1,2,0,...,111.5,62.90,155.6,72.6,124.9,69.4,71.9,0,NaN,0.3720

In [86]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      3500 non-null   int64
 1   gender                   3500 non-null   int64
 2   bmi                      3500 non-null   float64
 3   smoking_status           3500 non-null   int64
 4   alcohol_consumption      3500 non-null   int64
 5   exercise_level           3500 non-null   int64
 6   diet_type                3500 non-null   int64
 7   sun_exposure             3500 non-null   int64
 8   income_level             3500 non-null   int64
 9   latitude_region          3500 non-null   int64
 10  vitamin_a_percent_rda    3500 non-null   float64
 11  vitamin_c_percent_rda    3500 non-null   float64
 12  vitamin_d_percent_rda    3500 non-null   float64
 13  vitamin_e_percent_rda    3500 non-null   float64
 14  vitamin_b12_percent_rda  3500 non-null   float64
 15  folate_percent_rda       3500 non-null   float64
 16  calcium_percent_rda      3500 non-null   float64
 17  iron_percent_rda         3500 non-null   float64
 18  symptoms_count           3500 non-null   int64
 19  symptoms_list            2348 non-null   str
 20  vitamin_deficiency       3500 non-null   float64
dtypes: float64(10), int64(10), str(1)
memory usage: 574.3 KB

In [ ]:
#correlation matrix

In [ ]:
all_symptoms = set()

for i, count in df['symptoms_list'].value_counts().items():
    symptoms = i.split(';')
    all_symptoms.update(symptoms)
    # print(f"{i}: {count}")

numbness_tingling;memory_problems: 211
bone_pain;muscle_weakness: 167
numbness_tingling: 110
bone_pain: 104
fatigue: 97
bone_pain;numbness_tingling;muscle_weakness;memory_problems: 87
bone_pain;numbness_tingling;memory_problems: 82
muscle_weakness: 75
pale_skin;fatigue: 71
numbness_tingling;memory_problems;muscle_weakness: 56
memory_problems: 54
numbness_tingling;memory_problems;fatigue: 43
bone_pain;numbness_tingling;muscle_weakness: 41
numbness_tingling;memory_problems;pale_skin;fatigue: 40
dry_skin;night_blindness: 37
muscle_weakness;bone_pain;numbness_tingling;memory_problems;fatigue: 34
muscle_weakness;bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue: 34
night_blindness: 30
bone_pain;fatigue;muscle_weakness: 26
numbness_tingling;pale_skin;fatigue: 26
bone_pain;numbness_tingling: 25
bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue: 25
bone_pain;memory_problems;muscle_weakness: 23
bone_pain;pale_skin;fatigue;muscle_weakness: 23
muscle_weakness;bone_pain;numbness_tingling;pale_skin;fatigue: 21
bone_pain;fatigue: 19
muscle_weakness;numbness_tingling;memory_problems;pale_skin;fatigue: 18
bone_pain;numbness_tingling;fatigue;memory_problems: 18
bleeding_gums;fatigue: 18
bone_pain;numbness_tingling;pale_skin;fatigue: 17
pale_skin: 16
memory_problems;muscle_weakness: 16
numbness_tingling;muscle_weakness: 16
bone_pain;memory_problems: 15
fatigue;muscle_weakness: 15
bone_pain;numbness_tingling;fatigue;muscle_weakness: 14
bone_pain;dry_skin;muscle_weakness;night_blindness: 14
bone_pain;muscle_weakness;night_blindness: 13
numbness_tingling;fatigue: 13
numbness_tingling;memory_problems;pale_skin: 13
pale_skin;fatigue;muscle_weakness: 12
bone_pain;pale_skin;fatigue: 12
bone_pain;numbness_tingling;fatigue: 12
numbness_tingling;bleeding_gums;fatigue;memory_problems: 12
numbness_tingling;memory_problems;dry_skin;night_blindness: 11
memory_problems;pale_skin;fatigue: 11
numbness_tingling;memory_problems;fatigue;muscle_weakness: 11
bone_pain;bleeding_gums;fatigue;muscle_weakness: 10
dry_skin: 9
muscle_weakness;bone_pain;numbness_tingling;memory_problems;pale_skin: 9
numbness_tingling;memory_problems;night_blindness: 9
numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 9
numbness_tingling;night_blindness: 8
bleeding_gums: 8
numbness_tingling;pale_skin;fatigue;muscle_weakness: 8
muscle_weakness;bone_pain;memory_problems;pale_skin;fatigue: 8
dry_skin;fatigue;night_blindness: 7
fatigue;night_blindness: 7
dry_skin;numbness_tingling;night_blindness;memory_problems;fatigue: 7
muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 7
pale_skin;dry_skin;fatigue;night_blindness: 7
numbness_tingling;dry_skin;night_blindness: 6
memory_problems;fatigue: 6
bone_pain;bleeding_gums;numbness_tingling;memory_problems;pale_skin;fatigue: 6
memory_problems;dry_skin;night_blindness: 6
bone_pain;pale_skin;muscle_weakness: 6
dry_skin;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 6
muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems: 6
bone_pain;memory_problems;fatigue;muscle_weakness: 6
dry_skin;numbness_tingling;night_blindness;pale_skin;fatigue: 6
bone_pain;memory_problems;fatigue: 5
numbness_tingling;memory_problems;pale_skin;muscle_weakness: 5
muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;memory_problems;pale_skin;fatigue: 5
numbness_tingling;bleeding_gums;fatigue: 5
numbness_tingling;fatigue;muscle_weakness: 5
bone_pain;bleeding_gums;fatigue: 5
numbness_tingling;pale_skin: 5
bone_pain;dry_skin;muscle_weakness: 5
bone_pain;memory_problems;pale_skin;fatigue: 5
bleeding_gums;fatigue;memory_problems: 4
dry_skin;bone_pain;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 4
bone_pain;dry_skin;fatigue;night_blindness: 4
bone_pain;bleeding_gums: 4
muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;fatigue: 4
bone_pain;pale_skin: 4
dry_skin;muscle_weakness;night_blindness: 4
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 4
memory_problems;night_blindness: 4
bone_pain;numbness_tingling;dry_skin;night_blindness: 4
muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;memory_problems;fatigue: 4
bleeding_gums;fatigue;muscle_weakness: 4
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness: 4
bone_pain;bleeding_gums;numbness_tingling;memory_problems;fatigue: 4
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems;fatigue: 4
memory_problems;pale_skin;muscle_weakness: 3
dry_skin;bone_pain;numbness_tingling;night_blindness;memory_problems: 3
pale_skin;dry_skin;fatigue: 3
muscle_weakness;bone_pain;night_blindness;pale_skin;fatigue: 3
muscle_weakness;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 3
pale_skin;fatigue;night_blindness: 3
bleeding_gums;night_blindness: 3
dry_skin;numbness_tingling;memory_problems;pale_skin;fatigue: 3
numbness_tingling;memory_problems;muscle_weakness;night_blindness: 3
muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems;fatigue: 3
pale_skin;muscle_weakness: 3
memory_problems;pale_skin;fatigue;muscle_weakness: 3
pale_skin;dry_skin;night_blindness: 3
pale_skin;fatigue;muscle_weakness;night_blindness: 3
dry_skin;muscle_weakness;bone_pain;night_blindness;fatigue: 3
bone_pain;numbness_tingling;night_blindness;memory_problems: 3
numbness_tingling;bleeding_gums;memory_problems;pale_skin;fatigue: 3
dry_skin;muscle_weakness;bone_pain;numbness_tingling;memory_problems: 3
muscle_weakness;night_blindness: 3
bone_pain;numbness_tingling;pale_skin;memory_problems: 3
numbness_tingling;bleeding_gums;memory_problems: 3
numbness_tingling;dry_skin: 3
dry_skin;numbness_tingling;bleeding_gums;night_blindness;memory_problems;fatigue: 3
numbness_tingling;bleeding_gums;pale_skin;fatigue: 3
bone_pain;memory_problems;pale_skin;muscle_weakness: 3
bone_pain;dry_skin;night_blindness: 3
bleeding_gums;dry_skin;fatigue;night_blindness: 3
numbness_tingling;pale_skin;fatigue;night_blindness: 2
dry_skin;muscle_weakness;bone_pain;night_blindness;memory_problems;pale_skin;fatigue: 2
numbness_tingling;dry_skin;fatigue;night_blindness: 2
muscle_weakness;bone_pain;night_blindness;memory_problems;fatigue: 2
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems: 2
bleeding_gums;fatigue;night_blindness: 2
muscle_weakness;numbness_tingling;night_blindness;pale_skin;fatigue: 2
dry_skin;muscle_weakness;night_blindness;pale_skin;fatigue: 2
bone_pain;night_blindness;memory_problems;pale_skin;fatigue: 2
bone_pain;bleeding_gums;fatigue;numbness_tingling: 2
memory_problems;fatigue;muscle_weakness: 2
dry_skin;muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;night_blindness;memory_problems;fatigue: 2
bone_pain;bleeding_gums;muscle_weakness: 2
dry_skin;muscle_weakness;numbness_tingling;night_blindness;memory_problems: 2
numbness_tingling;memory_problems;pale_skin;night_blindness: 2
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness;fatigue: 2
bone_pain;memory_problems;pale_skin: 2
dry_skin;muscle_weakness;numbness_tingling;night_blindness;fatigue: 2
bone_pain;numbness_tingling;pale_skin;muscle_weakness: 2
muscle_weakness;numbness_tingling;bleeding_gums;memory_problems;pale_skin;fatigue: 2
bone_pain;fatigue;muscle_weakness;night_blindness: 2
bone_pain;bleeding_gums;numbness_tingling;muscle_weakness: 2
dry_skin;bone_pain;night_blindness;memory_problems;pale_skin;fatigue: 2
bone_pain;numbness_tingling;night_blindness;memory_problems;pale_skin;fatigue: 2
numbness_tingling;fatigue;night_blindness: 2
bleeding_gums;memory_problems: 2
muscle_weakness;bone_pain;night_blindness;memory_problems;pale_skin;fatigue: 2
dry_skin;numbness_tingling;bleeding_gums;night_blindness;fatigue: 2
bone_pain;pale_skin;fatigue;night_blindness: 2
bleeding_gums;fatigue;night_blindness;memory_problems: 2
numbness_tingling;dry_skin;muscle_weakness;night_blindness: 1
bone_pain;bleeding_gums;night_blindness;pale_skin;fatigue: 1
dry_skin;muscle_weakness;numbness_tingling;night_blindness;memory_problems;pale_skin: 1
numbness_tingling;pale_skin;dry_skin;night_blindness: 1
bone_pain;memory_problems;dry_skin;night_blindness: 1
bone_pain;bleeding_gums;pale_skin;fatigue: 1
dry_skin;bone_pain;bleeding_gums;night_blindness;fatigue: 1
muscle_weakness;numbness_tingling;bleeding_gums;memory_problems;fatigue: 1
dry_skin;night_blindness;memory_problems;pale_skin;fatigue: 1
numbness_tingling;pale_skin;muscle_weakness;night_blindness: 1
dry_skin;muscle_weakness;bone_pain;bleeding_gums;night_blindness;pale_skin;fatigue: 1
bone_pain;dry_skin: 1
dry_skin;numbness_tingling;bleeding_gums;memory_problems;fatigue: 1
numbness_tingling;pale_skin;dry_skin;fatigue: 1
muscle_weakness;bleeding_gums;memory_problems;pale_skin;fatigue: 1
bone_pain;memory_problems;night_blindness: 1
numbness_tingling;bleeding_gums;night_blindness;pale_skin;fatigue: 1
bone_pain;numbness_tingling;muscle_weakness;night_blindness: 1
numbness_tingling;bleeding_gums;night_blindness;memory_problems;fatigue: 1
dry_skin;bone_pain;bleeding_gums;numbness_tingling;night_blindness;memory_problems;fatigue: 1
dry_skin;muscle_weakness;numbness_tingling;night_blindness;pale_skin: 1
muscle_weakness;numbness_tingling;bleeding_gums;night_blindness;memory_problems: 1
muscle_weakness;bone_pain;numbness_tingling;night_blindness;pale_skin: 1
memory_problems;dry_skin;fatigue;night_blindness: 1
bone_pain;memory_problems;dry_skin: 1
bleeding_gums;pale_skin;fatigue;muscle_weakness: 1
pale_skin;night_blindness: 1
dry_skin;muscle_weakness;numbness_tingling;night_blindness;memory_problems;fatigue: 1
numbness_tingling;bleeding_gums: 1
dry_skin;bleeding_gums;night_blindness;pale_skin;fatigue: 1
fatigue;muscle_weakness;night_blindness: 1
bone_pain;night_blindness: 1
bone_pain;bleeding_gums;dry_skin;muscle_weakness: 1
pale_skin;muscle_weakness;night_blindness: 1
dry_skin;numbness_tingling;bleeding_gums;night_blindness;memory_problems;pale_skin;fatigue: 1
muscle_weakness;numbness_tingling;night_blindness;memory_problems;pale_skin: 1
dry_skin;muscle_weakness;bone_pain;numbness_tingling;memory_problems;pale_skin: 1
muscle_weakness;bleeding_gums;night_blindness;memory_problems;pale_skin;fatigue: 1
pale_skin;dry_skin;fatigue;muscle_weakness: 1
muscle_weakness;numbness_tingling;night_blindness;memory_problems;fatigue: 1
dry_skin;muscle_weakness;bone_pain;night_blindness;pale_skin;fatigue: 1
numbness_tingling;pale_skin;muscle_weakness: 1
bone_pain;bleeding_gums;muscle_weakness;memory_problems: 1
dry_skin;fatigue: 1
bone_pain;bleeding_gums;fatigue;memory_problems: 1
muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;night_blindness;pale_skin: 1
bone_pain;memory_problems;dry_skin;muscle_weakness: 1
dry_skin;muscle_weakness;numbness_tingling;night_blindness;pale_skin;fatigue: 1
numbness_tingling;memory_problems;fatigue;night_blindness: 1
dry_skin;muscle_weakness;bone_pain;memory_problems;pale_skin;fatigue: 1
muscle_weakness;bone_pain;bleeding_gums;memory_problems;pale_skin: 1
muscle_weakness;bone_pain;numbness_tingling;night_blindness;memory_problems;pale_skin: 1
dry_skin;bone_pain;bleeding_gums;numbness_tingling;night_blindness;fatigue: 1
bone_pain;numbness_tingling;dry_skin;memory_problems: 1
memory_problems;pale_skin: 1
muscle_weakness;bone_pain;bleeding_gums;memory_problems;pale_skin;fatigue: 1
dry_skin;muscle_weakness;bone_pain;night_blindness;memory_problems: 1
dry_skin;bone_pain;numbness_tingling;night_blindness;memory_problems;fatigue: 1
dry_skin;muscle_weakness;bone_pain;numbness_tingling;night_blindness;pale_skin;fatigue: 1
dry_skin;muscle_weakness;bone_pain;night_blindness;memory_problems;fatigue: 1
dry_skin;muscle_weakness;numbness_tingling;memory_problems;pale_skin;fatigue: 1
bone_pain;bleeding_gums;memory_problems;pale_skin;fatigue: 1
numbness_tingling;memory_problems;dry_skin;pale_skin: 1
muscle_weakness;bone_pain;numbness_tingling;night_blindness;pale_skin;fatigue: 1
dry_skin;muscle_weakness;bone_pain;pale_skin;fatigue: 1
muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;night_blindness;memory_problems;fatigue: 1
dry_skin;muscle_weakness;bone_pain;bleeding_gums;fatigue: 1
numbness_tingling;memory_problems;dry_skin;fatigue: 1
numbness_tingling;memory_problems;dry_skin: 1
memory_problems;pale_skin;fatigue;night_blindness: 1
dry_skin;muscle_weakness: 1
bone_pain;numbness_tingling;dry_skin;muscle_weakness: 1
dry_skin;muscle_weakness;bone_pain;bleeding_gums;numbness_tingling;night_blindness;pale_skin;fatigue: 1
dry_skin;numbness_tingling;bleeding_gums;night_blindness;memory_problems: 1
dry_skin;muscle_weakness;bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue: 1
numbness_tingling;bleeding_gums;fatigue;night_blindness: 1
dry_skin;bone_pain;numbness_tingling;memory_problems;pale_skin;fatigue: 1

In [88]:
all_symptoms

{'bleeding_gums',
 'bone_pain',
 'dry_skin',
 'fatigue',
 'memory_problems',
 'muscle_weakness',
 'night_blindness',
 'numbness_tingling',
 'pale_skin'}

In [95]:
df['symptoms_list'] = df['symptoms_list'].fillna("None")

In [96]:
#make columns for each symptom
for symptom in all_symptoms:
    df[symptom] = df['symptoms_list'].apply(lambda x: 1 if symptom in x.split(';') else 0)

In [98]:
df.drop('symptoms_list', axis=1, inplace=True)

In [99]:
df.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,vitamin_deficiency,night_blindness,dry_skin,memory_problems,pale_skin,numbness_tingling,bone_pain,fatigue,muscle_weakness,bleeding_gums
0,79,0,24.8,1,0,3,2,2,2,1,...,0.0000,0,0,0,0,0,0,0,0,0
1,77,1,39.9,1,1,1,3,0,0,0,...,0.8440,0,0,0,0,0,1,0,0,0
2,24,0,26.4,1,2,2,3,0,2,2,...,0.0040,1,1,0,0,0,0,0,0,0
3,69,0,23.1,2,2,2,2,2,0,0,...,0.7724,0,0,1,0,1,0,0,0,0
4,63,0,29.6,2,0,2,2,1,2,0,...,0.3720,0,0,0,0,0,0,0,0,0

In [100]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 29 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   age                      3500 non-null   int64
 1   gender                   3500 non-null   int64
 2   bmi                      3500 non-null   float64
 3   smoking_status           3500 non-null   int64
 4   alcohol_consumption      3500 non-null   int64
 5   exercise_level           3500 non-null   int64
 6   diet_type                3500 non-null   int64
 7   sun_exposure             3500 non-null   int64
 8   income_level             3500 non-null   int64
 9   latitude_region          3500 non-null   int64
 10  vitamin_a_percent_rda    3500 non-null   float64
 11  vitamin_c_percent_rda    3500 non-null   float64
 12  vitamin_d_percent_rda    3500 non-null   float64
 13  vitamin_e_percent_rda    3500 non-null   float64
 14  vitamin_b12_percent_rda  3500 non-null   float64
 15  folate_percent_rda       3500 non-null   float64
 16  calcium_percent_rda      3500 non-null   float64
 17  iron_percent_rda         3500 non-null   float64
 18  symptoms_count           3500 non-null   int64
 19  vitamin_deficiency       3500 non-null   float64
 20  night_blindness          3500 non-null   int64
 21  dry_skin                 3500 non-null   int64
 22  memory_problems          3500 non-null   int64
 23  pale_skin                3500 non-null   int64
 24  numbness_tingling        3500 non-null   int64
 25  bone_pain                3500 non-null   int64
 26  fatigue                  3500 non-null   int64
 27  muscle_weakness          3500 non-null   int64
 28  bleeding_gums            3500 non-null   int64
dtypes: float64(10), int64(19)
memory usage: 793.1 KB

In [102]:
pd.DataFrame(df).to_csv('train_data_processed.csv', index=False)

In [103]:
df.head()

,age,gender,bmi,smoking_status,alcohol_consumption,exercise_level,diet_type,sun_exposure,income_level,latitude_region,...,vitamin_deficiency,night_blindness,dry_skin,memory_problems,pale_skin,numbness_tingling,bone_pain,fatigue,muscle_weakness,bleeding_gums
0,79,0,24.8,1,0,3,2,2,2,1,...,0.0000,0,0,0,0,0,0,0,0,0
1,77,1,39.9,1,1,1,3,0,0,0,...,0.8440,0,0,0,0,0,1,0,0,0
2,24,0,26.4,1,2,2,3,0,2,2,...,0.0040,1,1,0,0,0,0,0,0,0
3,69,0,23.1,2,2,2,2,2,0,0,...,0.7724,0,0,1,0,1,0,0,0,0
4,63,0,29.6,2,0,2,2,1,2,0,...,0.3720,0,0,0,0,0,0,0,0,0

## split and train

In [106]:
## feature engineering
df = df.drop('symptoms_count', axis=1)

In [ ]:
#split
from sklearn.model_selection import train_test_split

X = df.drop(columns=["vitamin_deficiency"])
y = df["vitamin_deficiency"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [111]:
X_train.shape

(2800, 27)

In [112]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [113]:
# simple linear regression model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train_scaled, y_train)

LinearRegression()

In [114]:
model.score(X_test_scaled, y_test)

0.7858803147320272

In [ ]:
from sklearn.metrics import r2_score, mean_squared_error

In [120]:
y_pred = model.predict(X_test_scaled)
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.7858803147320272
Mean Squared Error: 0.04092788456439803
RMSE 0.20230641256371

In [123]:
# random forest regressor
from sklearn.ensemble import RandomForestRegressor
rf_model = RandomForestRegressor(n_estimators=300, random_state=42)
rf_model.fit(X_train_scaled, y_train)
rf_model.score(X_test_scaled, y_test)

0.8624135250982102

In [124]:
y_pred = rf_model.predict(X_test_scaled)
print("R2 Score:", r2_score(y_test, y_pred))
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("RMSE", np.sqrt(mean_squared_error(y_test, y_pred)))

R2 Score: 0.8624135250982102
Mean Squared Error: 0.026298952174133337
RMSE 0.16216951678454658

In [130]:
# polynomial regression
from sklearn.preprocessing import PolynomialFeatures


poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)


poly_model = LinearRegression()
poly_model.fit(X_train_poly, y_train)

poly_model.score(X_test_poly, y_test)

0.8461777505501871

In [131]:
df.duplicated().sum()

np.int64(0)